- hosts: localhost
  become: true
  vars_files:
    - ./.ssh/github_secrets.yml
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
        - ssh
        - dotfiles
        - core
        - git-personal
        - install
        - neovim
  tasks:
    - name: Include zsh tasks
      include_tasks: tasks/zsh.yml

    - name: Include node tasks
      include_tasks: tasks/node.yml

    - name: Include ssh tasks
      include_tasks: tasks/ssh.yml

    - name: Include dotfiles tasks
      include_tasks: tasks/dotfiles.yml

    - name: Include core setup tasks
      include_tasks: tasks/core-setup.yml

    - name: Include git setup tasks
      include_tasks: tasks/git-setup.yml
