---
- hosts: localhost
  vars_files:
    - ./.ssh/vault.yml
  pre_tasks:
    - name: Update cache on Debian-based systems
      become: yes
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"
      tags:
        - zsh
        - node
        - ssh
        - dotfiles
        - core
        - git-personal
        - install
        - neovim

    - name: Update cache on Arch-based systems
      become: yes
      pacman:
        update_cache: true
      when: ansible_facts['os_family'] == "Archlinux"
      tags:
        - zsh
        - node
        - ssh
        - dotfiles
        - core
        - git-personal
        - install
        - neovim

  tasks:
    - name: Include zsh tasks
      import_tasks: tasks/zsh.yml

    - name: Include node tasks
      import_tasks: tasks/node.yml

    - name: Include ssh tasks
      import_tasks: tasks/ssh.yml

    - name: Include dotfiles tasks
      import_tasks: tasks/dotfiles.yml

    - name: Include core setup tasks
      import_tasks: tasks/core-setup.yml

    - name: Include Neovim setup tasks
      import_tasks: tasks/nvim-setup.yml
