- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "h4z3m.private@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "h4z3m"
  tags:
  - git-personal
