- name: Determine OS family
  ansible.builtin.setup:
    filter: ansible_facts['os_family']

  tags:
    - ssh
    - git-personal
- name: Ensure Git is installed on Debian-based systems
  apt:
    name: git
    state: present
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - ssh
    - git-personal
- name: Ensure Git is installed on Arch-based systems
  pacman:
    name: git
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

  tags:
    - ssh
    - git-personal

- name: Configure Git with user name
  git_config:
    name: user.name
    value: "h4z3m"
    scope: global

  tags:
    - ssh
    - git-personal
- name: Configure Git with user email
  git_config:
    name: user.email
    value: "h4z3m.private@gmail.com"
    scope: global

  tags:
    - ssh
    - git-personal
- name: Ensure SSH directory exists
  file:
    path: /home/{{ ansible_user_id }}/.ssh
    state: directory
    mode: 0700
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - ssh
    - git-personal

- name: Deploy SSH private key
  copy:
    content: "{{ ssh_private_key }}"
    dest: /home/{{ ansible_user_id }}/.ssh/id_rsa
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - ssh
    - git-personal

- name: Deploy SSH public key
  copy:
    content: "{{ ssh_public_key }}"
    dest: /home/{{ ansible_user_id }}/.ssh/id_rsa.pub
    mode: '0644'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - ssh
    - git-personal

- name: Add GitHub to known hosts
  shell: ssh-keyscan -H github.com >> /home/{{ ansible_user_id }}/.ssh/known_hosts
  args:
    creates: /home/{{ ansible_user_id }}/.ssh/known_hosts
  tags:
    - ssh
    - git-personal

- name: Ensure known_hosts file has correct permissions
  file:
    path: /home/{{ ansible_user_id }}/.ssh/known_hosts
    mode: '0644'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - ssh
    - git-personal
