- name: Install ZSH
  apt: name=zsh 
  tags:
    - zsh
- name: Install shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh 
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Install zsh-vi-mode
  ansible.builtin.git:
    repo: "https://github.com/jeffreytse/zsh-vi-mode"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-vi-mode"
  tags:
    - zsh
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-vi-mode/' ~/.zshrc
  tags:
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - zsh
