
---
- name: Install Zsh on Debian-based systems
  become: true
  apt:
    name: zsh
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - zsh
- name: Install Zsh on Arch Linux
  become: true
  pacman:
    name: zsh
  when: ansible_facts['os_family'] == "Archlinux"
  tags:
    - zsh

- name: Install shell
  become: yes
  shell: chsh -s `which zsh`
  tags:
    - zsh

- name: Remove existing Oh My Zsh directory
  file:
    path: ~/.oh-my-zsh
    state: absent
  tags:
    - zsh

- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
      
- name: Install zsh-vi-mode
  ansible.builtin.git:
    repo: "https://github.com/jeffreytse/zsh-vi-mode"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-vi-mode"
  tags:
    - zsh
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-vi-mode/' ~/.zshrc
  tags:
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: yes
  tags:
    - zsh
